roles:
  master_coordinator:
    description: "Top-level coordinator responsible for delegating tasks."
    tools:
      - "workflow_manager"
  data_agent:
    description: "Agent responsible for data collection and cleaning."
    tools:
      - "data_tools"
  analysis_agent:
    description: "Agent that manages data analysis and modeling."
    tools:
      - "analysis_tools"
  visualization_agent:
    description: "Agent that generates visualizations and reports."
    tools:
      - "viz_tools"

relationships:
  master_coordinator:
    delegates_to:
      - "data_agent"
      - "analysis_agent"
      - "visualization_agent"
  data_agent:
    communicates_with:
      - "analysis_agent"
  analysis_agent:
    communicates_with:
      - "visualization_agent"

tool_settings:
  data_tools:
    libraries:
      - "pyjanitor"
      - "cleanlab"
  analysis_tools:
    libraries:
      - "pandas"
      - "numpy"
      - "scikit-learn"
  viz_tools:
    libraries:
      - "plotly"
      - "altair"